[dev]
  command = "pnpm dev"
  targetPort = 3000

[build.environment]
  NPM_FLAGS="--prefix=/"

[build]
  command = "pnpm build"
  publish = "build/"
  functions = "functions/"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true